#pragma once

#define COMMAND_VERSION "version"
#define COMMAND_HELP "help"
#define COMMAND_EXIT "exit"

#define COMMAND_PI "pi"

#define COMMAND_HMAP "hmap"
#define COMMAND_HMAP_GET "get"
#define COMMAND_HMAP_SET "set"
#define COMMAND_HMAP_DEL "del"
#define COMMAND_HMAP_CAP "cap"
#define COMMAND_HMAP_LEN "len"
#define COMMAND_HMAP_PRINT "print"

#define COMMAND_LRU "lru"
#define COMMAND_LRU_GET "get"
#define COMMAND_LRU_SET "set"
#define COMMAND_LRU_LEN "len"
#define COMMAND_LRU_CAP "cap"
#define COMMAND_LRU_PRINT "print"

#define COMMAND_AVL "avl"
#define COMMAND_AVL_GET "get"
#define COMMAND_AVL_SET "set"
#define COMMAND_AVL_PRINT "print"
#define COMMAND_AVL_IN "in"
#define COMMAND_AVL_PRE "pre"
#define COMMAND_AVL_POST "post"
#define COMMAND_AVL_DUMP "dump"

#define COMMAND_RBTREE "rbtree"
#define COMMAND_RBTREE_GET "get"
#define COMMAND_RBTREE_SET "set"
#define COMMAND_RBTREE_PRINT "print"
#define COMMAND_RBTREE_IN "in"
#define COMMAND_RBTREE_PRE "pre"
#define COMMAND_RBTREE_POST "post"
#define COMMAND_RBTREE_DUMP "dump"
#define COMMAND_RBTREE_DEL "del"

#define COMMAND_DEQUE "deque"
#define COMMAND_DEQUE_TEST "test"
#define COMMAND_DEQUE_DEL "del"
#define COMMAND_DEQUE_BACK "back"
#define COMMAND_DEQUE_FRONT "front"
#define COMMAND_DEQUE_PUSH "push"
#define COMMAND_DEQUE_POP "pop"
#define COMMAND_DEQUE_DUMP "dump"

#define COMMAND_STACK "stack"
#define COMMAND_STACK_PUSH "push"
#define COMMAND_STACK_POP "pop"
#define COMMAND_STACK_DUMP "dump"

#define COMMAND_BLOOM "bloom"
#define COMMAND_BLOOM_PUSH "push"
#define COMMAND_BLOOM_CHECK "check"

#define COMMAND_SKLIST "sklist"
#define COMMAND_SKLIST_SET "set"
#define COMMAND_SKLIST_GET "get"
#define COMMAND_SKLIST_DEL "del"

#define COMMAND_DAG "dag"
#define COMMAND_DAG_DUMP "dump"
#define COMMAND_DAG_TEST "test"
#define COMMAND_DAG_PRINT "print"
#define COMMAND_DAG_VERTEX "vertex"
#define COMMAND_DAG_VERTEX_ADD "add"
#define COMMAND_DAG_VERTEX_GET "get"
#define COMMAND_DAG_VERTEX_DEL "del"
#define COMMAND_DAG_EDGE "edge"
#define COMMAND_DAG_EDGE_ADD "add"
#define COMMAND_DAG_EDGE_DEL "del"

#define COMMAND_BITTREE "bittree"
#define COMMAND_BITTREE_ADD "add"
#define COMMAND_BITTREE_PRINT "print"
#define COMMAND_BITTREE_TEST "test"
