name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make all
      - name: show info
        run: |
          file bottle
          ldd bottle
          ls -Slh src/*.o bottle
